### ISSUE TITLE
Wrong value if space is in argument-value

### ISSUE THREAD

**Issue by mfreiholz** [adishavit/argh#17]
I want my program to start with a custom configuration file using the `--config` parameter. If the path to the configuration file contains a space, it doesn't work anymore.

```
myapp.exe --config="C:\Folder\With Space\Config.ini"
```

Results in value `C:\Folder\With` for `--config`.

```
	argh::parser cmdl(argc, argv);
	std::string argConfigFilePath;
	cmdl({ "-c", "--config" }) >> argConfigFilePath;
```

**Comment by adishavit** [comment]
The argument is actually parsed correctly. The problem is that streaming with `>>` into string, tokenizes on whitespace (this is a general C++ behavior not specific to Argh). 

Use the `.str()` method instead, as in:  
`cout << cmdl({ "-c", "--config" }).str() << endl;`

The `>>` streaming operator is mainly aimed at easy user-side type conversions.

**Comment by mfreiholz** [comment]
Okay. Thanks.
That may be worth mentioning in your docs, if it isn't. ;-)

**Comment by adishavit** [comment]
Done. Thanks!
