### ISSUE TITLE
Default string value doesn't support spaces

### ISSUE THREAD

**Issue by harry75369** [adishavit/argh#38]
```
#include <iostream>
#include "argh.h"

int main(int argc, char *argv[]) {
  argh::parser cmdl(argc, argv);

  std::string input = "Some default string value with spaces";
  std::string output;
  cmdl({"-o", "--output"}, input) >> output;

  std::cout << input << std::endl;
  std::cout << output<< std::endl;
  return 0;
}
```

Run it without any arguments.
Expected: output = "Some default string value with spaces"
Actual: output = "Some"

**Comment by adishavit** [comment]
Your code snippet is strange (misplaced `{}` and undefined `argc, argv` (probably because you edited it)).
However, in the readme **Tips** sections there is a bullet answering your questions (IIUC):

- When parsing parameter values as strings that may contain spaces  
(e.g. `--config="C:\Folder\With Space\Config.ini")`, prefer using `.str()` instead of `>>` to avoid the default automatic whitespace input stream tokenization:  
`cout << cmdl({ "-c", "--config" }).str().`

**Comment by harry75369** [comment]
Sorry, I have corrected my code and it compiles now.

According to your suggestion, I make changes as follows
```
cmdl({"-o", "--output"}, input) >> output;
// changes to
output = cmdl({"-o", "--output"}, input).str();
```
and it works. Thanks.

But my point is, since `input` here is provided as default fallback value when no arguments are provided, why tries to parse it? Is it possible to intelligently set `output = input` in this case?

**Comment by adishavit** [comment]
This is how string output-stream `>>` operators work. The “parsing” (tokenizing) you refer to happens on the user’s end. In *your* code, not in the library. Think of it as a feature. 
You could save the result stream (which does include the whole string with spaces) and read the tokens from it one by one, or read the whole thing with `.str()` as in your fixed example.

**Comment by harry75369** [comment]
OK, I see. Thanks for the clarification. Issue closed.
